from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[2]


def replace_once(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one anchor, found {count}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


state_receipts = ROOT / "codex-rs/core/src/state/tool_operation_receipts.rs"
state_receipts.write_text(
    dedent(
        '''\
        use std::collections::HashMap;

        use codex_tools::ToolOperationEffect;
        use codex_tools::ToolOperationReceipt;
        use codex_tools::ToolOperationTerminalState;

        const MAX_RETAINED_TOOL_OPERATION_RECEIPTS: usize = 1024;

        /// Stable identity for one logical tool operation.
        ///
        /// Direct calls use the Responses API call id. Nested Code Mode calls use the runtime's
        /// per-cell identity and deliberately ignore the synthetic host call id generated by Codex.
        #[derive(Clone, Debug, Eq, Hash, PartialEq)]
        pub(crate) enum ToolOperationId {
            Direct(String),
            CodeMode {
                cell_id: String,
                runtime_tool_call_id: String,
            },
        }

        impl ToolOperationId {
            pub(crate) fn direct(call_id: impl Into<String>) -> Self {
                Self::Direct(call_id.into())
            }
        }

        /// Session-scoped live owner for privacy-safe tool-operation receipts.
        ///
        /// This owner survives ordinary turn boundaries. Durable rollout restoration and
        /// compacted-checkpoint carry-forward are separate stages. The owner is bounded;
        /// overflow records permanent coverage loss so compaction can later fail closed.
        #[derive(Default)]
        pub(crate) struct ToolOperationReceipts {
            receipts: HashMap<ToolOperationId, ToolOperationReceipt>,
            coverage_lost: bool,
        }

        impl ToolOperationReceipts {
            pub(crate) fn begin(
                &mut self,
                operation_id: ToolOperationId,
                effect: ToolOperationEffect,
            ) {
                if let Some(receipt) = self.receipts.get_mut(&operation_id) {
                    receipt.effect = ToolOperationEffect::PotentialMutation;
                    receipt.record_terminal_outcome(ToolOperationTerminalState::Ambiguous);
                    receipt.record_result_ambiguous();
                    return;
                }

                if self.coverage_lost || self.receipts.len() >= MAX_RETAINED_TOOL_OPERATION_RECEIPTS {
                    self.coverage_lost = true;
                    return;
                }

                self.receipts
                    .insert(operation_id, ToolOperationReceipt::pending(effect));
            }

            pub(crate) fn record_terminal(
                &mut self,
                operation_id: &ToolOperationId,
                terminal_state: ToolOperationTerminalState,
            ) {
                let Some(receipt) = self.receipt_or_insert_conservative(operation_id) else {
                    return;
                };
                receipt.record_terminal_outcome(terminal_state);
            }

            pub(crate) fn record_result_persisted(&mut self, operation_id: &ToolOperationId) {
                let Some(receipt) = self.receipt_or_insert_conservative(operation_id) else {
                    return;
                };
                receipt.record_result_persisted();
            }

            pub(crate) fn record_result_ambiguous(&mut self, operation_id: &ToolOperationId) {
                let Some(receipt) = self.receipt_or_insert_conservative(operation_id) else {
                    return;
                };
                receipt.record_result_ambiguous();
            }

            pub(crate) fn receipt(
                &self,
                operation_id: &ToolOperationId,
            ) -> Option<ToolOperationReceipt> {
                self.receipts.get(operation_id).copied()
            }

            pub(crate) fn has_unreconciled_potential_mutation(&self) -> bool {
                self.coverage_lost
                    || self.receipts.values().any(|receipt| {
                        receipt.effect == ToolOperationEffect::PotentialMutation
                            && !receipt.is_compaction_ready()
                    })
            }

            pub(crate) fn coverage_lost(&self) -> bool {
                self.coverage_lost
            }

            fn receipt_or_insert_conservative(
                &mut self,
                operation_id: &ToolOperationId,
            ) -> Option<&mut ToolOperationReceipt> {
                if !self.receipts.contains_key(operation_id) {
                    if self.coverage_lost || self.receipts.len() >= MAX_RETAINED_TOOL_OPERATION_RECEIPTS {
                        self.coverage_lost = true;
                        return None;
                    }
                    self.receipts.insert(
                        operation_id.clone(),
                        ToolOperationReceipt::pending(ToolOperationEffect::PotentialMutation),
                    );
                }
                self.receipts.get_mut(operation_id)
            }
        }

        #[cfg(test)]
        #[path = "tool_operation_receipts_tests.rs"]
        mod tests;
        '''
    ),
    encoding="utf-8",
)

state_tests = ROOT / "codex-rs/core/src/state/tool_operation_receipts_tests.rs"
state_tests.write_text(
    dedent(
        '''\
        use super::*;
        use codex_tools::ToolOperationResultState;

        fn direct(call_id: &str) -> ToolOperationId {
            ToolOperationId::direct(call_id)
        }

        fn code_mode(cell_id: &str, runtime_tool_call_id: &str) -> ToolOperationId {
            ToolOperationId::CodeMode {
                cell_id: cell_id.to_string(),
                runtime_tool_call_id: runtime_tool_call_id.to_string(),
            }
        }

        #[test]
        fn potential_mutation_reconciles_after_terminal_and_result() {
            let mut receipts = ToolOperationReceipts::default();
            let id = direct("call-1");
            receipts.begin(id.clone(), ToolOperationEffect::PotentialMutation);
            assert!(receipts.has_unreconciled_potential_mutation());

            receipts.record_terminal(&id, ToolOperationTerminalState::Completed);
            assert!(receipts.has_unreconciled_potential_mutation());

            receipts.record_result_persisted(&id);
            assert!(!receipts.has_unreconciled_potential_mutation());
        }

        #[test]
        fn persistence_before_terminal_reconciles_when_terminal_arrives() {
            let mut receipts = ToolOperationReceipts::default();
            let id = direct("call-1");
            receipts.begin(id.clone(), ToolOperationEffect::PotentialMutation);
            receipts.record_result_persisted(&id);
            assert!(receipts.has_unreconciled_potential_mutation());

            receipts.record_terminal(&id, ToolOperationTerminalState::Completed);
            assert!(!receipts.has_unreconciled_potential_mutation());
        }

        #[test]
        fn duplicate_persistence_remains_ambiguous() {
            let mut receipts = ToolOperationReceipts::default();
            let id = direct("call-1");
            receipts.begin(id.clone(), ToolOperationEffect::PotentialMutation);
            receipts.record_terminal(&id, ToolOperationTerminalState::Completed);
            receipts.record_result_persisted(&id);
            receipts.record_result_persisted(&id);

            let receipt = receipts.receipt(&id).expect("receipt should exist");
            assert_eq!(receipt.result_state, ToolOperationResultState::Ambiguous);
            assert!(receipts.has_unreconciled_potential_mutation());
        }

        #[test]
        fn conflicting_terminal_outcomes_remain_ambiguous() {
            let mut receipts = ToolOperationReceipts::default();
            let id = direct("call-1");
            receipts.begin(id.clone(), ToolOperationEffect::PotentialMutation);
            receipts.record_terminal(&id, ToolOperationTerminalState::Completed);
            receipts.record_terminal(&id, ToolOperationTerminalState::Aborted);
            receipts.record_result_persisted(&id);

            let receipt = receipts.receipt(&id).expect("receipt should exist");
            assert_eq!(
                receipt.terminal_state,
                ToolOperationTerminalState::Ambiguous
            );
            assert!(receipts.has_unreconciled_potential_mutation());
        }

        #[test]
        fn repeated_begin_escalates_effect_and_marks_identity_ambiguous() {
            let mut receipts = ToolOperationReceipts::default();
            let id = direct("call-1");
            receipts.begin(id.clone(), ToolOperationEffect::ReadOnly);
            receipts.begin(id.clone(), ToolOperationEffect::PotentialMutation);

            let receipt = receipts.receipt(&id).expect("receipt should exist");
            assert_eq!(receipt.effect, ToolOperationEffect::PotentialMutation);
            assert_eq!(
                receipt.terminal_state,
                ToolOperationTerminalState::Ambiguous
            );
            assert_eq!(receipt.result_state, ToolOperationResultState::Ambiguous);
            assert!(receipts.has_unreconciled_potential_mutation());
        }

        #[test]
        fn late_observation_defaults_to_potential_mutation() {
            let mut receipts = ToolOperationReceipts::default();
            let id = direct("late-call");
            receipts.record_terminal(&id, ToolOperationTerminalState::Completed);

            let receipt = receipts
                .receipt(&id)
                .expect("late observation should create a conservative receipt");
            assert_eq!(receipt.effect, ToolOperationEffect::PotentialMutation);
            assert!(receipts.has_unreconciled_potential_mutation());
        }

        #[test]
        fn read_only_receipt_does_not_block_mutation_preflight() {
            let mut receipts = ToolOperationReceipts::default();
            receipts.begin(direct("read-1"), ToolOperationEffect::ReadOnly);
            assert!(!receipts.has_unreconciled_potential_mutation());
        }

        #[test]
        fn explicit_persistence_failure_stays_ambiguous() {
            let mut receipts = ToolOperationReceipts::default();
            let id = direct("call-1");
            receipts.begin(id.clone(), ToolOperationEffect::PotentialMutation);
            receipts.record_terminal(&id, ToolOperationTerminalState::Completed);
            receipts.record_result_ambiguous(&id);

            let receipt = receipts.receipt(&id).expect("receipt should exist");
            assert_eq!(receipt.result_state, ToolOperationResultState::Ambiguous);
            assert!(receipts.has_unreconciled_potential_mutation());
        }

        #[test]
        fn direct_and_code_mode_ids_do_not_collide() {
            let mut receipts = ToolOperationReceipts::default();
            let direct_id = direct("same-id");
            let nested_id = code_mode("cell-1", "same-id");

            receipts.begin(direct_id.clone(), ToolOperationEffect::ReadOnly);
            receipts.begin(nested_id.clone(), ToolOperationEffect::PotentialMutation);

            assert_eq!(
                receipts.receipt(&direct_id).expect("direct receipt").effect,
                ToolOperationEffect::ReadOnly
            );
            assert_eq!(
                receipts.receipt(&nested_id).expect("nested receipt").effect,
                ToolOperationEffect::PotentialMutation
            );
        }

        #[test]
        fn code_mode_runtime_ids_are_scoped_by_cell() {
            let mut receipts = ToolOperationReceipts::default();
            let first = code_mode("cell-1", "runtime-1");
            let second = code_mode("cell-2", "runtime-1");

            receipts.begin(first.clone(), ToolOperationEffect::ReadOnly);
            receipts.begin(second.clone(), ToolOperationEffect::PotentialMutation);

            assert_eq!(
                receipts.receipt(&first).expect("first cell receipt").effect,
                ToolOperationEffect::ReadOnly
            );
            assert_eq!(
                receipts.receipt(&second).expect("second cell receipt").effect,
                ToolOperationEffect::PotentialMutation
            );
        }

        #[test]
        fn overflow_sets_coverage_lost_and_fails_closed_without_eviction() {
            let mut receipts = ToolOperationReceipts::default();
            for index in 0..MAX_RETAINED_TOOL_OPERATION_RECEIPTS {
                receipts.begin(
                    direct(&format!("call-{index}")),
                    ToolOperationEffect::PotentialMutation,
                );
            }

            let overflow = direct("overflow");
            receipts.begin(overflow.clone(), ToolOperationEffect::PotentialMutation);

            assert!(receipts.coverage_lost());
            assert!(receipts.has_unreconciled_potential_mutation());
            assert!(receipts.receipt(&direct("call-0")).is_some());
            assert!(receipts.receipt(&overflow).is_none());
        }
        '''
    ),
    encoding="utf-8",
)

state_mod = ROOT / "codex-rs/core/src/state/mod.rs"
replace_once(
    state_mod,
    "pub(crate) use tool_operation_receipts::ToolOperationReceipts;\n",
    "pub(crate) use tool_operation_receipts::ToolOperationId;\npub(crate) use tool_operation_receipts::ToolOperationReceipts;\n",
    "state operation id export",
)

context = ROOT / "codex-rs/core/src/tools/context.rs"
replace_once(
    context,
    "use crate::session::turn_context::TurnContext;\n",
    "use crate::session::turn_context::TurnContext;\nuse crate::state::ToolOperationId;\n",
    "context operation id import",
)
replace_once(
    context,
    dedent(
        '''\
        #[derive(Clone, Debug, Eq, PartialEq)]
        pub enum ToolCallSource {
            Direct,
            CodeMode {
                /// Runtime cell that issued the nested tool request.
                cell_id: String,
                /// Code-mode's per-cell tool invocation id. This is useful for
                /// debugging the JS/runtime bridge, but it is not the Codex tool call id
                /// because the runtime id only needs to be unique within one cell.
                runtime_tool_call_id: String,
            },
        }
        '''
    ),
    dedent(
        '''\
        #[derive(Clone, Debug, Eq, PartialEq)]
        pub enum ToolCallSource {
            Direct,
            CodeMode {
                /// Runtime cell that issued the nested tool request.
                cell_id: String,
                /// Code-mode's per-cell tool invocation id. This is useful for
                /// debugging the JS/runtime bridge, but it is not the Codex tool call id
                /// because the runtime id only needs to be unique within one cell.
                runtime_tool_call_id: String,
            },
        }

        impl ToolCallSource {
            pub(crate) fn operation_id(&self, direct_call_id: &str) -> ToolOperationId {
                match self {
                    Self::Direct => ToolOperationId::direct(direct_call_id),
                    Self::CodeMode {
                        cell_id,
                        runtime_tool_call_id,
                    } => ToolOperationId::CodeMode {
                        cell_id: cell_id.clone(),
                        runtime_tool_call_id: runtime_tool_call_id.clone(),
                    },
                }
            }
        }
        '''
    ),
    "tool source operation identity",
)
replace_once(
    context,
    dedent(
        '''\
        pub struct ToolInvocation {
            pub session: Arc<Session>,
            // TODO(sayan): Remove this compatibility field once handlers use `step_context.turn`.
            pub turn: Arc<TurnContext>,
            pub(crate) step_context: Arc<StepContext>,
            pub cancellation_token: CancellationToken,
            pub tracker: SharedTurnDiffTracker,
            pub call_id: String,
            pub tool_name: ToolName,
            pub source: ToolCallSource,
            pub payload: ToolPayload,
        }
        '''
    ),
    dedent(
        '''\
        pub struct ToolInvocation {
            pub session: Arc<Session>,
            // TODO(sayan): Remove this compatibility field once handlers use `step_context.turn`.
            pub turn: Arc<TurnContext>,
            pub(crate) step_context: Arc<StepContext>,
            pub cancellation_token: CancellationToken,
            pub tracker: SharedTurnDiffTracker,
            pub call_id: String,
            pub tool_name: ToolName,
            pub source: ToolCallSource,
            pub payload: ToolPayload,
        }

        impl ToolInvocation {
            pub(crate) fn operation_id(&self) -> ToolOperationId {
                self.source.operation_id(&self.call_id)
            }
        }
        '''
    ),
    "invocation operation identity",
)

session_operation = ROOT / "codex-rs/core/src/session/tool_operation.rs"
session_operation.write_text(
    dedent(
        '''\
        use codex_tools::ToolOperationEffect;
        use codex_tools::ToolOperationReceipt;
        use codex_tools::ToolOperationTerminalState;

        use crate::state::ToolOperationId;

        use super::session::Session;

        impl Session {
            pub(crate) async fn begin_tool_operation_receipt(
                &self,
                call_id: String,
                effect: ToolOperationEffect,
            ) {
                self.begin_tool_operation_receipt_for_id(ToolOperationId::direct(call_id), effect)
                    .await;
            }

            pub(crate) async fn begin_tool_operation_receipt_for_id(
                &self,
                operation_id: ToolOperationId,
                effect: ToolOperationEffect,
            ) {
                self.state
                    .lock()
                    .await
                    .tool_operation_receipts
                    .begin(operation_id, effect);
            }

            pub(crate) async fn record_tool_operation_terminal(
                &self,
                call_id: &str,
                terminal_state: ToolOperationTerminalState,
            ) {
                let operation_id = ToolOperationId::direct(call_id);
                self.record_tool_operation_terminal_for_id(&operation_id, terminal_state)
                    .await;
            }

            pub(crate) async fn record_tool_operation_terminal_for_id(
                &self,
                operation_id: &ToolOperationId,
                terminal_state: ToolOperationTerminalState,
            ) {
                self.state
                    .lock()
                    .await
                    .tool_operation_receipts
                    .record_terminal(operation_id, terminal_state);
            }

            pub(crate) async fn record_tool_operation_result_persisted(&self, call_id: &str) {
                let operation_id = ToolOperationId::direct(call_id);
                self.record_tool_operation_result_persisted_for_id(&operation_id)
                    .await;
            }

            pub(crate) async fn record_tool_operation_result_persisted_for_id(
                &self,
                operation_id: &ToolOperationId,
            ) {
                self.state
                    .lock()
                    .await
                    .tool_operation_receipts
                    .record_result_persisted(operation_id);
            }

            pub(crate) async fn record_tool_operation_result_ambiguous(&self, call_id: &str) {
                let operation_id = ToolOperationId::direct(call_id);
                self.record_tool_operation_result_ambiguous_for_id(&operation_id)
                    .await;
            }

            pub(crate) async fn record_tool_operation_result_ambiguous_for_id(
                &self,
                operation_id: &ToolOperationId,
            ) {
                self.state
                    .lock()
                    .await
                    .tool_operation_receipts
                    .record_result_ambiguous(operation_id);
            }

            pub(crate) async fn tool_operation_receipt(
                &self,
                call_id: &str,
            ) -> Option<ToolOperationReceipt> {
                let operation_id = ToolOperationId::direct(call_id);
                self.tool_operation_receipt_for_id(&operation_id).await
            }

            pub(crate) async fn tool_operation_receipt_for_id(
                &self,
                operation_id: &ToolOperationId,
            ) -> Option<ToolOperationReceipt> {
                self.state
                    .lock()
                    .await
                    .tool_operation_receipts
                    .receipt(operation_id)
            }

            pub(crate) async fn has_unreconciled_potential_mutation(&self) -> bool {
                self.state
                    .lock()
                    .await
                    .tool_operation_receipts
                    .has_unreconciled_potential_mutation()
            }
        }
        '''
    ),
    encoding="utf-8",
)

registry = ROOT / "codex-rs/core/src/tools/registry.rs"
replace_once(
    registry,
    "        let call_id_owned = invocation.call_id.clone();\n        let otel = invocation.turn.session_telemetry.clone();\n",
    "        let call_id_owned = invocation.call_id.clone();\n        let operation_id = invocation.operation_id();\n        let otel = invocation.turn.session_telemetry.clone();\n",
    "registry operation id capture",
)
replace_once(
    registry,
    "                    .begin_tool_operation_receipt(call_id_owned.clone(), tool.operation_effect())\n",
    "                    .begin_tool_operation_receipt_for_id(operation_id.clone(), tool.operation_effect())\n",
    "selected runtime typed receipt begin",
)
replace_once(
    registry,
    dedent(
        '''\
                        .begin_tool_operation_receipt(
                            call_id_owned.clone(),
                            ToolOperationEffect::PotentialMutation,
                        )
        '''
    ),
    dedent(
        '''\
                        .begin_tool_operation_receipt_for_id(
                            operation_id.clone(),
                            ToolOperationEffect::PotentialMutation,
                        )
        '''
    ),
    "unsupported runtime typed receipt begin",
)
replace_once(
    registry,
    dedent(
        '''\
            invocation
                .session
                .record_tool_operation_terminal(&invocation.call_id, terminal_state)
                .await;
        '''
    ),
    dedent(
        '''\
            let operation_id = invocation.operation_id();
            invocation
                .session
                .record_tool_operation_terminal_for_id(&operation_id, terminal_state)
                .await;
        '''
    ),
    "registry typed terminal observation",
)

lifecycle = ROOT / "codex-rs/core/src/tools/lifecycle.rs"
replace_once(
    lifecycle,
    dedent(
        '''\
            session
                .record_tool_operation_terminal(call_id, receipt_terminal_state(outcome))
                .await;
        '''
    ),
    dedent(
        '''\
            let operation_id = source.operation_id(call_id);
            session
                .record_tool_operation_terminal_for_id(
                    &operation_id,
                    receipt_terminal_state(outcome),
                )
                .await;
        '''
    ),
    "lifecycle typed terminal observation",
)

registry_tests = ROOT / "codex-rs/core/src/tools/registry_tests.rs"
text = registry_tests.read_text(encoding="utf-8")
test_name = "code_mode_receipt_uses_runtime_identity_instead_of_host_call_id"
if test_name in text:
    raise SystemExit(f"{test_name} already exists")
text += dedent(
    r'''

#[tokio::test]
async fn code_mode_receipt_uses_runtime_identity_instead_of_host_call_id() -> anyhow::Result<()> {
    let (session, turn) = crate::session::tests::make_session_and_context().await;
    let tool_name = codex_tools::ToolName::plain("code_mode_receipt");
    let handler = Arc::new(ReadOnlyTestHandler {
        tool_name: tool_name.clone(),
    }) as Arc<dyn CoreToolRuntime>;
    let registry = ToolRegistry::new(HashMap::from([(tool_name.clone(), handler)]));
    let session = Arc::new(session);
    let mut invocation = test_invocation(
        Arc::clone(&session),
        Arc::new(turn),
        "synthetic-host-call",
        tool_name,
    );
    invocation.source = crate::tools::context::ToolCallSource::CodeMode {
        cell_id: "cell-7".to_string(),
        runtime_tool_call_id: "runtime-3".to_string(),
    };

    registry
        .dispatch_any_with_terminal_outcome(invocation, None)
        .await?;

    assert!(
        session
            .tool_operation_receipt("synthetic-host-call")
            .await
            .is_none(),
        "synthetic host id must not own the nested receipt"
    );
    let operation_id = crate::state::ToolOperationId::CodeMode {
        cell_id: "cell-7".to_string(),
        runtime_tool_call_id: "runtime-3".to_string(),
    };
    let receipt = session
        .tool_operation_receipt_for_id(&operation_id)
        .await
        .expect("logical Code Mode receipt should exist");
    assert_eq!(receipt.effect, codex_tools::ToolOperationEffect::ReadOnly);
    assert_eq!(
        receipt.terminal_state,
        codex_tools::ToolOperationTerminalState::Completed
    );
    Ok(())
}
'''
)
registry_tests.write_text(text, encoding="utf-8")
